Vérification des outils de versionnement avant utilisation, afin d'éviter des erreurs. (#87)

diff --git a/pkg++.in b/pkg++.in
--- a/pkg++.in
+++ b/pkg++.in
@@ -137,6 +137,13 @@ check_file() {
 	fi
 }
 
+check_command() {
+	if [[ -z "`type -p $1`" ]]; then
+		error "Command '$1' not found."
+		exit 1
+	fi
+}
+
 list_includes() {
 	for include in `ls /usr/share/pkg++/includes/`; do
 		if grep -q "build()" /usr/share/pkg++/includes/$include; then
@@ -155,10 +162,7 @@ download_file() {
 	PROTOCOL="`get_protocol $1`"
 	case $PROTOCOL in
 		"http"|"https"|"ftp"|"file")
-			if [[ ! "`type -p wget`" ]]; then
-				error "Command 'wget' not found."
-				exit 1
-			fi
+			check_command "wget"
 			
 			LOCAL_FILENAME=`get_filename $1`
 			LOCAL_FILENAME_PARTIAL="$LOCAL_FILENAME.partial"
@@ -205,6 +209,7 @@ download_file() {
 			mv -f "$LOCAL_FILENAME_PARTIAL" "$LOCAL_FILENAME"
 		;;
 		"svn")
+			check_command "svn"
 			cd $PKGMK_SOURCE_DIR
 			if cd $name 2&> /dev/null; then
 				if [[ "`LANG=en_US.utf8 svn up`" =~ 'At revision '*'.' ]]; then
@@ -219,11 +224,13 @@ download_file() {
 			cd $PKGMK_SOURCE_DIR
 			if cd $name 2&> /dev/null; then
 				if [[ "$PROTOCOL" = "git" ]]; then
+					check_command "git"
 					if [[ "`git pull`" = "Already up-to-date." ]] && [[ "$PKGMK_FORCE" != "yes" ]]; then
 						info "Already up-to-date."
 						exit 0
 					fi
 				else
+					check_command "hg"
 					if [[ "`hg pull | tail -n 1`" = "no changes found" ]] && [[ "$PKGMK_FORCE" != "yes" ]]; then
 						info "Already up-to-date."
 						exit 0
@@ -236,6 +243,7 @@ download_file() {
 			fi
 		;;
 		"bzr")
+			check_command "bzr"
 			cd $PKGMK_SOURCE_DIR
 			if cd $name 2&> /dev/null; then
 				if [[ "`bzr update 2>&1`" =~ "Tree is up to date at revision ".*" of branch ".* ]] && [[ "$PKGMK_FORCE" != "yes" ]]; then
